name: Comment Listener

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print comment
        run: echo "${{ github.event.comment.body }}"
